### ISSUE TITLE
Missing BoatTitle.css

### ISSUE THREAD

**Issue by sauloefo** [anilsomasundaran/Lightning-Component-Framework-Specialist#2]
Hey @anilsomasundaran ,

First of all, thank you so much for sharing your solution and congratulations for complete it.
I've tried to find your css file for BoatTile component. Do you mind to add it? I'm stuck on it: I am not doing the css selector correctly.

All the best,

Saulo

**Comment by anilsomasundaran** [comment]
Sure. I will try to add the missing css today itself.



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Saulo Oliveira <notifications@github.com> Date: 03/09/2018  12:51 am  (GMT+05:30) To: anilsomasundaran/Lightning-Component-Framework-Specialist <Lightning-Component-Framework-Specialist@noreply.github.com> Cc: anilsomasundaran <anilsomasundarana@gmail.com>, Mention <mention@noreply.github.com> Subject: [anilsomasundaran/Lightning-Component-Framework-Specialist] Missing BoatTitle.css (#2) 
Hey @anilsomasundaran ,
First of all, thank you so much for sharing your solution and congratulations for complete it.

I've tried to find your css file for BoatTile component. Do you mind to add it? I'm stuck on it: I am not doing the css selector correctly.
All the best,
Saulo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anilsomasundaran/Lightning-Component-Framework-Specialist","title":"anilsomasundaran/Lightning-Component-Framework-Specialist","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/anilsomasundaran/Lightning-Component-Framework-Specialist"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Missing BoatTitle.css (#2)"}],"action":{"name":"View Issue","url":"https://github.com/anilsomasundaran/Lightning-Component-Framework-Specialist/issues/2"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/anilsomasundaran/Lightning-Component-Framework-Specialist/issues/2",
"url": "https://github.com/anilsomasundaran/Lightning-Component-Framework-Specialist/issues/2",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Missing BoatTitle.css (#2)",
"sections": [
{
"text": "",
"activityTitle": "**Saulo Oliveira**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@sauloefo",
"facts": [
{
"name": "Repository: ",
"value": "anilsomasundaran/Lightning-Component-Framework-Specialist"
},
{
"name": "Issue #: ",
"value": 2
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"anilsomasundaran/Lightning-Component-Framework-Specialist\",\n\"issueId\": 2,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"anilsomasundaran/Lightning-Component-Framework-Specialist\",\n\"issueId\": 2\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/anilsomasundaran/Lightning-Component-Framework-Specialist/issues/2"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 375057788\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by anilsomasundaran** [comment]
abhirajpr / Lightning-Component-Framework-Specialist
Code  Issues 0  Pull requests 0  Projects 0  Pulse
src/aura/BoatTile/BoatTile.css

.THIS.tile {
   position:relative;
   display: inline-block;
   background-size: cover;
   background-position: center;
   background-repeat: no-repeat;

   height: 220px;
   padding: 1px !important;
   
}
.THIS.selected {

   border:3px solid rgb(0, 112, 210);
}

.THIS .innertile {
   background-size: cover;
   background-position: center;
   background-repeat: no-repeat;
   width: 220px;
   height: 100%;
}

.THIS .lower-third {
   position: absolute;
   bottom: 0;
   left: 0;
   right: 0;
   color: #FFFFFF;
   background-color: rgba(0, 0, 0, .4);
   padding: 6px 8px;
}
 Desktop version

**Comment by sauloefo** [comment]
The 100% width specification (as mentioned in the exercise) in innerTile class was broken my layout. I was thinking I wasn't getting something in the Lightning CSS.
Seriously man. You save my day! Thanks a million!
